//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicenseShow_TrialCheck.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LicenseShow_TrialCheck.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;&lt;Modulus&gt;6bf3wGITyddFsoM9bpSshn2VaISrS/e4HvP0ZbuFU/iqHC5ZUlX6ufKOvp5lMfpkq6TmqM0HK8Had1+S10103Tc+oq7zp1NsyZihTBqHyJGyIQpE+/typsGqllqrBwW08XQWU4kSqpuCUyhYw5xIcqc25uLty1gvwZUuDJoMI3xlREjBcpM3E1DKTbSjElfLjfh6ECKNxT7bU9IQxqSOd2Tr2Z4VyOaXMjZ7m0NoMcTVM9PO2kO60jel5uQCotSxZGCfgbvaXAEfUYrIY366r0ELmKU/o1SJJAa2HmiWh4x5xTd1RA4TWG8qCAJpXk8hOQ7C5HsAlbi/wIVInuftHgbnIpHTQB3U5A/Nceaq7xCYfVUG1ykHL084cifArePLNqXV80A+95+st7uLqeuAj42HcR8wog2iZVzMScCi7yk+WVvtXQKaRU4mAQpiELq6sdAHEDHPWAYz/Fl5LDSuqWWVrxDfPuALnESWX2lOE1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PubKey {
            get {
                return ResourceManager.GetString("PubKey", resourceCulture);
            }
        }
    }
}
